### ISSUE TITLE
Retry API errors?

### ISSUE THREAD

**Issue by steviehs** [stecklars/dynamic-dns-netcup-api#23]
Thanks for the script!

While using it, (via cron every 5 min) I get around every 5th time an API error:

[2022/11/07 00:10:04 +0100][ERROR] cURL Error: (22) The requested URL returned error: 504  - Exiting.

(sometimes other errors)

I am using the script with cronic, which sends me a mail every time the code produces output on stderr, which is desired, as you don't want to have cron jobs, which are more or less death since months but you do not see it, as you are not informed. But with the situation right now I get around 100 mails per day with error messages :-)
So I think, it would be nice to add a kind of an error counter (or timer) to the API calls and give it multiple retries over multiple calls?

What do you think?

**Comment by mwester117** [comment]
Hello @steviehs,

I have observed the same behavior. The script is not usable if you schedule it via cron and want to get mails if an output is produced. I don't even know if it occurs while trying to get the current IP address from ipfy.org or if it happens when using the netcup API. I'm not a php developer but I will check if I get some time these days and implement some kind of retry when an http request fails.

**Comment by stecklars** [comment]
Hi @steviehs and @mwester117,

Thank you for your reports.

This should be fixed now in the newest release version 4.0:
https://github.com/stecklars/dynamic-dns-netcup-api/releases/tag/v4.0

The script will try each API action, in case there is an error, for three times, with a cooldown period of 30 seconds in between the tries. Warnings will not be output to stderr anymore, if the quiet option is used.
